### ISSUE TITLE
Does echo support basic widget like input field and scroll list on android

### ISSUE THREAD

**Issue by codingwatching** [timi-liuliang/echo#1045]
Hi @timi-liuliang 
I just want to use echo to build a game on Android device
Is this support basic control likes input field with keyboard, scroll list yet?
Thank you so much!

**Comment by timi-liuliang** [comment]
no, only button image label was supported now.

**Comment by codingwatching** [comment]
Thank you! I hope we can add the widget system to the engine soon! I personally recommend adding IMGUI to the engine!
(https://github.com/ocornut/imgui)

And we also need to add Input Field with the soft keyboard to mobile devices likes android and ios.
Thank you so much!
