### ISSUE TITLE
Unmovable asset icons

### ISSUE THREAD

**Issue by ghost** [timi-liuliang/echo#240]
Arrange the icons via grid and unmovable inside the asset panel (to avoid overlapping the icons with other assets).

![zxc](https://user-images.githubusercontent.com/41359801/48006121-1625a800-e150-11e8-8441-c3f9d907764f.JPG)

**Comment by timi-liuliang** [comment]
Hi, I have implemented this task for you. Please Download the new installer

[echo-setup-2018.11.06.exe](https://media.githubusercontent.com/media/blab-liuliang/echo-download/master/download/echo-setup-2018.11.06.exe). 

If it doesn't meet your need. please reopen this issue.  and tell me the reason.

**Comment by timi-liuliang** [comment]
echo-setup-2018.11.06.exe's size is about 47.2M, Before you start this install application,  Make sure you download it succeed.
