### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by ghost** [timi-liuliang/echo#245]
What version do I need? I am using the 2017 Community version on most of my stuff, but I am getting this error when using cmake. (Sorry I am a bit inexperienced on manually compiling or doing stuff)

I am trying to compile a latest version with 64 bit windows support, the last time you uploaded has an error. And I am currently checking the source code.

![capture](https://user-images.githubusercontent.com/41359801/48842073-42872880-edce-11e8-97ec-f2bec1c0ea5f.PNG)

**Comment by timi-liuliang** [comment]
Open Visual Studio
Go to Tools -> Get Tools and Features
In the "Workloads" tab enable "Desktop development with C++"
Click Modify at the bottom right

![](https://raw.githubusercontent.com/wiki/blab-liuliang/echo/image/editor/compile/cplusplusforvisualstudio.png)

Then Try [Use CMake Directly](https://github.com/blab-liuliang/echo/wiki/Compile-Echo-From-Source-Code)
