### ISSUE TITLE
Very cool project - I have some questions below

### ISSUE THREAD

**Issue by trsh** [timi-liuliang/echo#541]
Questions:

1) Is there a penalty in performance using Lua for logic?
2) How do I use C++ directly not changing the SDK, like project scope code?
3) What about IK, skeletal animations?
4) It says 'no Prefab'. But let's say I have multiple copies of some Objects/nodes (ex. some model and it's props) and then I wish, when I change one, all related change? How can I accomplish that?
5) What's the tech for light and shadows? Probes? VXGI? Shadow maps?
6) Can I add custom shaders for objects and post processing?
7) 3d Physics?
8) UI creator/editor?
9) What the deal with the Houdini?

**Comment by trsh** [comment]
@timi-liuliang pls :))))

**Comment by timi-liuliang** [comment]
1. Yes,  Lua is slower than c, but Lua is still the fastest dynamic programming language on this planet.
[Is Lua really fast?](https://github.com/timi-liuliang/echo/wiki/FAQ-Script#1-is-lua-really-fast-)
2.  For now, we can extend the engine in a modular way, create a module and register in the editor, then we can enable/disable it. Add a new module allows for adding new functionality without modifying the core.
In the future, I hope we can extend the engine in a plugin way, a plugin is an external module and compiled as a dynamic library.
3.
