### ISSUE TITLE
Downloaded binaries do not work in windows 10 64x

### ISSUE THREAD

**Issue by trsh** [timi-liuliang/echo#542]
![error](https://user-images.githubusercontent.com/3727523/72687865-ca6bde00-3b0a-11ea-9834-4518fd8173de.png)

**Comment by timi-liuliang** [comment]
Sorry, try copy OpenAl32.dll to editor directory
https://github.com/timi-liuliang/echo/tree/master/bin/editor/Win64/Release

**Comment by trsh** [comment]
Ok, will try later
