### ISSUE TITLE
编辑器删除根节点时会报错

### ISSUE THREAD

**Issue by drakefang** [timi-liuliang/echo#543]
大概看了下在
NodeTreePanel::onDeleteNodes()
里面，调用removeItem的时候，会删除根节点，但是EchoEgine那边未得到通知
导致m_currentEditNode变成dangling
导致后续调用
EchoEngine::instance()->setCurrentEditNode(nullptr)
的时候就会报错

还在学习研究中，所以暂时还未推pr

**Comment by timi-liuliang** [comment]
1.导致崩溃的BUG已修改(简单测试)
2.因为场景必须拥有一个主节点，否则无法保存，所以禁用了删除主节点功能
3.但是可以修改主节点的类型(Change Type)
4.可以在资源面板中删除场景文件
