### ISSUE TITLE
Can't build editor on windows 10 64x

### ISSUE THREAD

**Issue by trsh** [timi-liuliang/echo#548]
```
C:\Projects\echo\forks\echo\build\editor\win64>cmake.bat

C:\Projects\echo\forks\echo\build\editor\win64>call python build.py -make=cmake
CMake Error at CMakeLists.txt:9 (PROJECT):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Projects/echo/forks/echo/solution/CMakeFiles/CMakeOutput.log".
Press any key to continue . . .
```

I have VS 2017 and 2019 installed !!

**Comment by trsh** [comment]
Most likely from with my VS setups. Will reinstall and report back.

**Comment by trsh** [comment]
Nope. Same problem. 

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt

is present. "Desktop development with c++" installed. PC restarted 

:((

**Comment by trsh** [comment]
Moved this to SO, as it is obvious non this project problem

https://stackoverflow.com/questions/59953960/problems-with-cmake-and-vs-2017

**Comment by timi-liuliang** [comment]
Try this tutorial https://github.com/timi-liuliang/echo/wiki/Compile-Echo-From-Source-Code, That script depends on Visual studio's environment.
My fault, I'll modify it.
