### ISSUE TITLE
[FR] Move to VS 2019

### ISSUE THREAD

**Issue by trsh** [timi-liuliang/echo#549]

**Comment by timi-liuliang** [comment]
OK, please wait a few days, I have no windows machine now.

**Comment by trsh** [comment]
@timi-liuliang maybe u have 5 min to answer my questions in https://github.com/timi-liuliang/echo/issues/541 . Please :)

**Comment by timi-liuliang** [comment]
You can [Compile With VS2019](https://github.com/timi-liuliang/echo/wiki/FAQ-Compile) Now.
