### ISSUE TITLE
Prebuilt bin still doesn't work on win 64x

### ISSUE THREAD

**Issue by theqwave** [timi-liuliang/echo#556]
![2020-02-09_170013](https://user-images.githubusercontent.com/60447735/74104496-dec95680-4b5d-11ea-8e99-bf6af236c7c8.png)

**Comment by timi-liuliang** [comment]
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I think you should update [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe)

Reference:
1. [StackOverFlow-Questions-58828982](https://stackoverflow.com/questions/58828982/vcruntime140-1-dll-missing-after-building-solution-with-c)

**Comment by timi-liuliang** [comment]
Is this answer solved your problem? If not, please reopen this issue.
