### ISSUE TITLE
Terrain example fails

### ISSUE THREAD

**Issue by trsh** [timi-liuliang/echo#609]
FileHandleDataStream fopen [C:/Users/trsh/Downloads/echo-examples-master/echo-examples-master/terrain/scene/four_wheels.scene] failed
Error: Cannot open file: Res://scene/four_wheels.scene in FileSystem::open[No such file or directory]
Node::load failed. path [Res://scene/four_wheels.scene] not exist

Windows 10 64x, GPU GTX 750 Ti (up to date drivers)

**Comment by timi-liuliang** [comment]
Go into the menu : Project->Settings->GameSettings

then set LaunchScene to Res://scene/terrain.scene
