### ISSUE TITLE
is there any demo for android

### ISSUE THREAD

**Issue by jaccen** [timi-liuliang/echo#627]

**Comment by jaccen** [comment]
i have build app/android . but  no test demo. how can i run a scrip's demo under android platform ?

**Comment by timi-liuliang** [comment]
only build for ios and windows platform is supported now.

**Comment by timi-liuliang** [comment]
You can build the examples by tutorial 
https://github.com/timi-liuliang/echo/wiki/BuildForAndroid

[build-house-debug.apk](https://github.com/timi-liuliang/echo-examples/releases/tag/build-house-1.0)
