### ISSUE TITLE
Can't find a download link for Mac.

### ISSUE THREAD

**Issue by SirBuildsALot** [timi-liuliang/echo#731]
Under the downloads section, the Mac echo.dmg was just some text instead of a download link.

**Comment by Ryuu22** [comment]
I noticed the same. I am keen to test the engine on Mac but I believe they aren't releasing a mac version just yet. You could compile it yourself but I hope the .dmg is available soon as well.

**Comment by timi-liuliang** [comment]
Now you can download here https://github.com/timi-liuliang/echo/releases
