### ISSUE TITLE
System Error: OpenCL.dll was not found

### ISSUE THREAD

**Issue by peratik** [timi-liuliang/echo#735]
Windows 10 64 bit

Error ScreenShot:
![image](https://user-images.githubusercontent.com/6568353/93427931-deebba80-f8d3-11ea-92b4-fed8745cb1fb.png)

Please advice.

**Comment by timi-liuliang** [comment]
AMD GPU?

**Comment by peratik** [comment]
NVIDIA GeForce GT 540M

**Comment by timi-liuliang** [comment]
Sorry, Try to fix it like this now https://www.drivereasy.com/knowledge/solved-opencl-dll-missing-or-not-found-errors/
I‘ll add the OpenCL.dll into echo windows editor's directory in the near future.
