### ISSUE TITLE
Make a website to make it popular

### ISSUE THREAD

**Issue by Nep-Toodles** [timi-liuliang/echo#772]
Like godot and unity or unreaal make a website with assets store and other discusiions tools and with docummentaion. 
also a paterion with  donation this will help you a lot.

**Comment by timi-liuliang** [comment]
There is still a lot of work to be done before the publicity, like 
Render Pipeline visualization. 
General Procedural Content Generation. 
Scratch support
Linux platform support
Lua Debugger
etc...
